import { Organization } from '../domain/types';

export const mockOrganizations: Organization[] = [
  {
    id: 'org-demo-001',
    referenceId: 'org-ref-001',
    name: 'Acme Cloud',
    description: 'Synthetic cloud operations workspace.',
    address: '100 Demo Avenue',
    city: 'Austin',
    region: 'TX',
    postalCode: '78701',
    country: 'US',
    timezone: 'America/Chicago',
    domains: [
      { name: 'acme-cloud.example', userCount: 34, status: 'verified' },
      { name: 'ops.acme-cloud.example', userCount: 14, status: 'verified' },
    ],
    admins: [
      {
        id: 'admin-demo-001',
        referenceId: 'admin-ref-001',
        firstName: 'Jordan',
        lastName: 'Lee',
        email: 'jordan.lee@acme-cloud.example',
      },
      {
        id: 'admin-demo-002',
        referenceId: 'admin-ref-002',
        firstName: 'Mina',
        lastName: 'Patel',
        email: 'mina.patel@acme-cloud.example',
      },
    ],
    createdOn: '2025-08-04T14:16:00.000Z',
    lastUpdatedOn: '2026-05-22T16:42:00.000Z',
    userCount: 48,
    adminCount: 2,
    status: 'active',
  },
  {
    id: 'org-demo-002',
    referenceId: 'org-ref-002',
    name: 'Northstar Labs',
    description: 'Synthetic research operations tenant.',
    address: '240 Sample Street',
    city: 'Portland',
    region: 'OR',
    postalCode: '97205',
    country: 'US',
    timezone: 'America/Los_Angeles',
    domains: [
      { name: 'northstar-labs.example', userCount: 20, status: 'verified' },
      { name: 'research.northstar-labs.example', userCount: 4, status: 'inactive' },
    ],
    admins: [
      {
        id: 'admin-demo-003',
        referenceId: 'admin-ref-003',
        firstName: 'Sam',
        lastName: 'Rivera',
        email: 'sam.rivera@northstar-labs.example',
      },
    ],
    createdOn: '2025-09-11T10:08:00.000Z',
    lastUpdatedOn: '2026-05-18T09:20:00.000Z',
    userCount: 24,
    adminCount: 1,
    status: 'inactive',
  },
  {
    id: 'org-demo-003',
    referenceId: 'org-ref-003',
    name: 'Vertex Systems',
    description: 'Synthetic enterprise systems workspace.',
    address: '48 Example Plaza',
    city: 'Chicago',
    region: 'IL',
    postalCode: '60601',
    country: 'US',
    timezone: 'America/Chicago',
    domains: [
      { name: 'vertex-systems.example', userCount: 49, status: 'verified' },
      { name: 'platform.vertex-systems.example', userCount: 23, status: 'verified' },
    ],
    admins: [
      {
        id: 'admin-demo-004',
        referenceId: 'admin-ref-004',
        firstName: 'Avery',
        lastName: 'Chen',
        email: 'avery.chen@vertex-systems.example',
      },
      {
        id: 'admin-demo-005',
        referenceId: 'admin-ref-005',
        firstName: 'Taylor',
        lastName: 'Morgan',
        email: 'taylor.morgan@vertex-systems.example',
        disabled: true,
      },
    ],
    createdOn: '2025-06-19T18:04:00.000Z',
    lastUpdatedOn: '2026-05-26T11:35:00.000Z',
    userCount: 72,
    adminCount: 2,
    status: 'active',
  },
  {
    id: 'org-demo-004',
    referenceId: 'org-ref-004',
    name: 'Summit Works',
    description: 'Synthetic archived operations account.',
    address: '19 Portfolio Road',
    city: 'Denver',
    region: 'CO',
    postalCode: '80202',
    country: 'US',
    timezone: 'America/Denver',
    domains: [{ name: 'summit-works.example', userCount: 8, status: 'disabled' }],
    admins: [
      {
        id: 'admin-demo-006',
        referenceId: 'admin-ref-006',
        firstName: 'Casey',
        lastName: 'Nguyen',
        email: 'casey.nguyen@summit-works.example',
        disabled: true,
      },
    ],
    createdOn: '2024-12-02T20:24:00.000Z',
    lastUpdatedOn: '2026-04-14T13:08:00.000Z',
    userCount: 8,
    adminCount: 1,
    status: 'archived',
  },
  {
    id: 'org-demo-005',
    referenceId: 'org-ref-005',
    name: 'Brightlane Studio',
    description: 'Synthetic design operations workspace.',
    address: '77 Sample Lane',
    city: 'Raleigh',
    region: 'NC',
    postalCode: '27601',
    country: 'US',
    timezone: 'America/New_York',
    domains: [
      { name: 'brightlane-studio.example', userCount: 16, status: 'verified' },
      { name: 'creative.brightlane-studio.example', userCount: 3, status: 'verified' },
    ],
    admins: [
      {
        id: 'admin-demo-007',
        referenceId: 'admin-ref-007',
        firstName: 'Riley',
        lastName: 'Stone',
        email: 'riley.stone@brightlane-studio.example',
      },
    ],
    createdOn: '2025-10-21T15:12:00.000Z',
    lastUpdatedOn: '2026-05-24T08:18:00.000Z',
    userCount: 19,
    adminCount: 1,
    status: 'active',
  },
  {
    id: 'org-demo-006',
    referenceId: 'org-ref-006',
    name: 'Harbor Ops',
    description: 'Synthetic field operations tenant.',
    address: '5 Mock Harbor Way',
    city: 'Seattle',
    region: 'WA',
    postalCode: '98101',
    country: 'US',
    timezone: 'America/Los_Angeles',
    domains: [{ name: 'harbor-ops.example', userCount: 31, status: 'verified' }],
    admins: [
      {
        id: 'admin-demo-008',
        referenceId: 'admin-ref-008',
        firstName: 'Morgan',
        lastName: 'Diaz',
        email: 'morgan.diaz@harbor-ops.example',
      },
    ],
    createdOn: '2025-11-06T12:00:00.000Z',
    lastUpdatedOn: '2026-05-20T17:10:00.000Z',
    userCount: 31,
    adminCount: 1,
    status: 'active',
  },
];
