import { Prisma } from '@prisma/client';
import { ORGANIZATION_IDS, ROLE_KEYS } from '../domain/adminConstants';

export const seedUsers: Prisma.UserCreateManyInput[] = [
  {
    id: 'user-platform-support',
    email: 'jordan.lee@platform-ops.example',
    firstName: 'Jordan',
    lastName: 'Lee',
    accountStatus: 'Active',
    lastSignedIn: new Date('2026-05-26T15:48:00.000Z'),
    createdAt: new Date('2025-08-04T14:16:00.000Z'),
    updatedAt: new Date('2026-05-26T15:48:00.000Z'),
  },
  {
    id: 'user-platform-lead',
    email: 'casey.nolan@platform-ops.example',
    firstName: 'Casey',
    lastName: 'Nolan',
    accountStatus: 'Active',
    lastSignedIn: new Date('2026-05-27T11:20:00.000Z'),
    createdAt: new Date('2025-08-12T09:30:00.000Z'),
    updatedAt: new Date('2026-05-27T11:20:00.000Z'),
  },
  {
    id: 'user-tenant-admin',
    email: 'mina.patel@acme-cloud.example',
    firstName: 'Mina',
    lastName: 'Patel',
    accountStatus: 'Active',
    lastSignedIn: new Date('2026-05-25T20:10:00.000Z'),
    createdAt: new Date('2025-09-11T10:08:00.000Z'),
    updatedAt: new Date('2026-05-25T20:10:00.000Z'),
  },
  {
    id: 'user-tenant-member',
    email: 'sam.rivera@acme-cloud.example',
    firstName: 'Sam',
    lastName: 'Rivera',
    accountStatus: 'Active',
    lastSignedIn: null,
    createdAt: new Date('2025-10-21T15:12:00.000Z'),
    updatedAt: new Date('2026-05-24T13:26:00.000Z'),
  },
  {
    id: 'user-multi-tenant-admin',
    email: 'taylor.morgan@admin-demo.example',
    firstName: 'Taylor',
    lastName: 'Morgan',
    accountStatus: 'Active',
    lastSignedIn: new Date('2026-05-18T09:20:00.000Z'),
    createdAt: new Date('2025-11-06T12:00:00.000Z'),
    updatedAt: new Date('2026-05-23T10:18:00.000Z'),
  },
  {
    id: 'user-platform-public-admin',
    email: 'avery.chen@platform-ops.example',
    firstName: 'Avery',
    lastName: 'Chen',
    accountStatus: 'Active',
    lastSignedIn: new Date('2026-05-28T10:14:00.000Z'),
    createdAt: new Date('2025-08-19T11:25:00.000Z'),
    updatedAt: new Date('2026-05-28T10:14:00.000Z'),
  },
  {
    id: 'user-vertex-member',
    email: 'riley.stone@vertex-systems.example',
    firstName: 'Riley',
    lastName: 'Stone',
    accountStatus: 'Incomplete',
    lastSignedIn: null,
    createdAt: new Date('2026-01-17T12:00:00.000Z'),
    updatedAt: new Date('2026-01-17T12:00:00.000Z'),
  },
  {
    id: 'user-public-new-001',
    email: 'alex.kim@public-signups.example',
    firstName: 'Alex',
    lastName: 'Kim',
    accountStatus: 'Incomplete',
    lastSignedIn: null,
    createdAt: new Date('2026-05-01T09:00:00.000Z'),
    updatedAt: new Date('2026-05-01T09:00:00.000Z'),
  },
  {
    id: 'user-public-new-002',
    email: 'jamie.ross@public-signups.example',
    firstName: 'Jamie',
    lastName: 'Ross',
    accountStatus: 'Incomplete',
    lastSignedIn: null,
    createdAt: new Date('2026-05-04T13:20:00.000Z'),
    updatedAt: new Date('2026-05-04T13:20:00.000Z'),
  },
  {
    id: 'user-public-new-003',
    email: 'quinn.parker@public-signups.example',
    firstName: 'Quinn',
    lastName: 'Parker',
    accountStatus: 'Active',
    lastSignedIn: new Date('2026-05-12T15:30:00.000Z'),
    createdAt: new Date('2026-05-08T08:45:00.000Z'),
    updatedAt: new Date('2026-05-12T15:30:00.000Z'),
  },
];

export const seedOrganizations: Prisma.OrganizationCreateManyInput[] = [
  {
    id: ORGANIZATION_IDS.platformOps,
    referenceId: 'org-ref-platform',
    name: 'Demo Platform Operations',
    kind: 'internal',
    description: 'Synthetic internal platform operations organization.',
    address: '1 Platform Way',
    city: 'Austin',
    region: 'TX',
    postalCode: '78701',
    country: 'US',
    timezone: 'America/Chicago',
    domainName: 'platform-ops.example',
    status: 'active',
    createdAt: new Date('2025-08-04T14:16:00.000Z'),
    updatedAt: new Date('2026-05-27T11:20:00.000Z'),
  },
  {
    id: ORGANIZATION_IDS.public,
    referenceId: 'org-ref-public',
    name: 'Public',
    kind: 'public',
    description:
      'Synthetic virtual organization for self-registered users without tenant membership.',
    address: 'Public Signup Pool',
    city: 'Remote',
    region: 'NA',
    postalCode: '00000',
    country: 'US',
    timezone: 'UTC',
    domainName: 'public-signups.example',
    status: 'active',
    createdAt: new Date('2026-05-01T09:00:00.000Z'),
    updatedAt: new Date('2026-05-28T10:14:00.000Z'),
  },
  {
    id: 'org-demo-001',
    referenceId: 'org-ref-001',
    name: 'Acme Cloud',
    kind: 'tenant',
    description: 'Synthetic cloud operations tenant.',
    address: '100 Demo Avenue',
    city: 'Austin',
    region: 'TX',
    postalCode: '78701',
    country: 'US',
    timezone: 'America/Chicago',
    domainName: 'acme-cloud.example',
    status: 'active',
    createdAt: new Date('2025-09-11T10:08:00.000Z'),
    updatedAt: new Date('2026-05-22T16:42:00.000Z'),
  },
  {
    id: 'org-demo-002',
    referenceId: 'org-ref-002',
    name: 'Northstar Labs',
    kind: 'tenant',
    description: 'Synthetic research operations tenant.',
    address: '240 Sample Street',
    city: 'Portland',
    region: 'OR',
    postalCode: '97205',
    country: 'US',
    timezone: 'America/Los_Angeles',
    domainName: 'northstar-labs.example',
    status: 'active',
    createdAt: new Date('2025-10-21T15:12:00.000Z'),
    updatedAt: new Date('2026-05-18T09:20:00.000Z'),
  },
  {
    id: 'org-demo-003',
    referenceId: 'org-ref-003',
    name: 'Vertex Systems',
    kind: 'tenant',
    description: 'Synthetic enterprise systems tenant.',
    address: '48 Example Plaza',
    city: 'Chicago',
    region: 'IL',
    postalCode: '60601',
    country: 'US',
    timezone: 'America/Chicago',
    domainName: 'vertex-systems.example',
    status: 'inactive',
    createdAt: new Date('2025-06-19T18:04:00.000Z'),
    updatedAt: new Date('2026-05-26T11:35:00.000Z'),
  },
];

export const seedRoles: Prisma.RoleCreateManyInput[] = [
  { id: 'role-platform-admin', key: ROLE_KEYS.platformAdmin, name: 'Platform Administrator' },
  {
    id: 'role-organization-admin',
    key: ROLE_KEYS.organizationAdmin,
    name: 'Organization Administrator',
  },
  { id: 'role-workspace-manager', key: ROLE_KEYS.workspaceManager, name: 'Workspace Manager' },
  {
    id: 'role-public-user-admin',
    key: ROLE_KEYS.publicUserAdmin,
    name: 'Public User Administrator',
  },
];

export const seedMemberships: Prisma.OrganizationMembershipCreateManyInput[] = [
  {
    id: 'membership-platform-support',
    userId: 'user-platform-support',
    organizationId: 'org-platform-ops',
    membershipStatus: 'active',
    createdAt: new Date('2025-08-04T14:20:00.000Z'),
    updatedAt: new Date('2025-08-04T14:20:00.000Z'),
  },
  {
    id: 'membership-platform-lead',
    userId: 'user-platform-lead',
    organizationId: 'org-platform-ops',
    membershipStatus: 'active',
    createdAt: new Date('2025-08-12T09:35:00.000Z'),
    updatedAt: new Date('2025-08-12T09:35:00.000Z'),
  },
  {
    id: 'membership-platform-public-admin',
    userId: 'user-platform-public-admin',
    organizationId: ORGANIZATION_IDS.platformOps,
    membershipStatus: 'active',
    createdAt: new Date('2025-08-19T11:30:00.000Z'),
    updatedAt: new Date('2025-08-19T11:30:00.000Z'),
  },
  {
    id: 'membership-acme-admin',
    userId: 'user-tenant-admin',
    organizationId: 'org-demo-001',
    membershipStatus: 'active',
    createdAt: new Date('2025-09-11T10:10:00.000Z'),
    updatedAt: new Date('2025-09-11T10:10:00.000Z'),
  },
  {
    id: 'membership-acme-member',
    userId: 'user-tenant-member',
    organizationId: 'org-demo-001',
    membershipStatus: 'active',
    createdAt: new Date('2025-10-21T15:16:00.000Z'),
    updatedAt: new Date('2025-10-21T15:16:00.000Z'),
  },
  {
    id: 'membership-northstar-admin',
    userId: 'user-multi-tenant-admin',
    organizationId: 'org-demo-002',
    membershipStatus: 'active',
    createdAt: new Date('2025-11-06T12:05:00.000Z'),
    updatedAt: new Date('2025-11-06T12:05:00.000Z'),
  },
  {
    id: 'membership-vertex-admin',
    userId: 'user-multi-tenant-admin',
    organizationId: 'org-demo-003',
    membershipStatus: 'active',
    createdAt: new Date('2025-11-07T12:05:00.000Z'),
    updatedAt: new Date('2025-11-07T12:05:00.000Z'),
  },
  {
    id: 'membership-vertex-member',
    userId: 'user-vertex-member',
    organizationId: 'org-demo-003',
    membershipStatus: 'active',
    createdAt: new Date('2026-01-17T12:05:00.000Z'),
    updatedAt: new Date('2026-01-17T12:05:00.000Z'),
  },
  {
    id: 'membership-public-new-001',
    userId: 'user-public-new-001',
    organizationId: ORGANIZATION_IDS.public,
    membershipStatus: 'active',
    createdAt: new Date('2026-05-01T09:00:00.000Z'),
    updatedAt: new Date('2026-05-01T09:00:00.000Z'),
  },
  {
    id: 'membership-public-new-002',
    userId: 'user-public-new-002',
    organizationId: ORGANIZATION_IDS.public,
    membershipStatus: 'active',
    createdAt: new Date('2026-05-04T13:20:00.000Z'),
    updatedAt: new Date('2026-05-04T13:20:00.000Z'),
  },
  {
    id: 'membership-public-new-003',
    userId: 'user-public-new-003',
    organizationId: ORGANIZATION_IDS.public,
    membershipStatus: 'active',
    createdAt: new Date('2026-05-08T08:45:00.000Z'),
    updatedAt: new Date('2026-05-08T08:45:00.000Z'),
  },
];

export const seedRoleAssignments: Prisma.MembershipRoleAssignmentCreateManyInput[] = [
  {
    id: 'assignment-platform-support-admin',
    membershipId: 'membership-platform-support',
    roleId: 'role-platform-admin',
  },
  {
    id: 'assignment-platform-lead-platform-admin',
    membershipId: 'membership-platform-lead',
    roleId: 'role-platform-admin',
  },
  {
    id: 'assignment-platform-lead-org-admin',
    membershipId: 'membership-platform-lead',
    roleId: 'role-organization-admin',
  },
  {
    id: 'assignment-platform-public-admin-platform-admin',
    membershipId: 'membership-platform-public-admin',
    roleId: 'role-platform-admin',
  },
  {
    id: 'assignment-platform-public-admin-public-user-admin',
    membershipId: 'membership-platform-public-admin',
    roleId: 'role-public-user-admin',
  },
  {
    id: 'assignment-acme-admin',
    membershipId: 'membership-acme-admin',
    roleId: 'role-organization-admin',
  },
  {
    id: 'assignment-northstar-admin',
    membershipId: 'membership-northstar-admin',
    roleId: 'role-organization-admin',
  },
  {
    id: 'assignment-vertex-admin',
    membershipId: 'membership-vertex-admin',
    roleId: 'role-organization-admin',
  },
];

export const seedActivityEvents: Prisma.ActivityEventCreateManyInput[] = [
  {
    id: 'activity-demo-001',
    actorUserId: 'user-tenant-admin',
    targetUserId: 'user-tenant-member',
    organizationId: 'org-demo-001',
    action: 'ADD_USER_TO_ORGANIZATION',
    result: 'success',
    message: 'Mina Patel added Sam Rivera to Acme Cloud.',
    metadataJson: JSON.stringify({ nextRoleKeys: [] }),
    createdAt: new Date('2026-05-26T15:48:00.000Z'),
  },
  {
    id: 'activity-demo-002',
    actorUserId: 'user-tenant-admin',
    targetUserId: 'user-tenant-member',
    organizationId: 'org-demo-001',
    action: 'CHANGE_USER_ROLES',
    result: 'success',
    message: 'Mina Patel changed roles for Sam Rivera in Acme Cloud.',
    metadataJson: JSON.stringify({
      previousRoleKeys: [],
      nextRoleKeys: ['organization_admin'],
    }),
    createdAt: new Date('2026-05-25T20:10:00.000Z'),
  },
  {
    id: 'activity-demo-003',
    actorUserId: 'user-platform-lead',
    targetUserId: 'user-multi-tenant-admin',
    organizationId: 'org-demo-002',
    action: 'SUSPEND_USER',
    result: 'success',
    message: 'Casey Nolan reviewed Taylor Morgan.',
    metadataJson: JSON.stringify({ reason: 'Synthetic access review outcome' }),
    createdAt: new Date('2026-05-23T10:18:00.000Z'),
  },
  {
    id: 'activity-demo-004',
    actorUserId: 'user-platform-support',
    organizationId: 'org-demo-001',
    action: 'ORGANIZATION_UPDATED',
    result: 'success',
    message: 'Jordan Lee updated organization settings for Acme Cloud.',
    metadataJson: JSON.stringify({ changedFields: ['city', 'timezone'] }),
    createdAt: new Date('2026-05-22T16:42:00.000Z'),
  },
  {
    id: 'activity-demo-005',
    targetUserId: 'user-vertex-member',
    action: 'UNKNOWN',
    result: 'unknown',
    message: 'System Automation recorded an unmapped user activity.',
    metadataJson: JSON.stringify({ reason: 'Synthetic fallback event' }),
    createdAt: new Date('2026-05-20T08:00:00.000Z'),
  },
];
